kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: /src/github.com/c-bata/kube-prompt

steps:
  - name: build
    image: golang:1.11
    commands:
      - git fetch
      - apt-get update && apt-get install -y zip
      - make setup
      - dep ensure
      - make cross
  - name: github_binary_release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - pkg/*
      checksum:
        - sha256
    when:
      instance:
      - drone-publish.rancher.io
      ref:
      - refs/head/master
      - refs/tags/*
      event:
      - tag
